apiVersion: snapshot.upjet-provider-outscale.upbound.io/v1alpha1
kind: Snapshot
metadata:
  name: cp-snap
  namespace: default
spec:
  forProvider:
    description: "my-snap"
    volumeIdRef:
      name: cp-volume
    tags:
      - key: Name
        value: cp-snap
  providerConfigRef:
    name: default 
---
apiVersion: snapshot.upjet-provider-outscale.upbound.io/v1alpha1
kind: SnapshotAttributes
metadata:
  name: snapattribute
  namespace: default
spec:
  forProvider:
    permissionsToCreateVolumeAdditions:
      - accountIds:
        - "027440686109"
    snapshotIdRef:
      name: cp-snap
  providerConfigRef:
    name: default 
