apiVersion: volume.upjet-provider-outscale.upbound.io/v1alpha1
kind: Volume
metadata:
  name: cp-volume
  namespace: default
spec:
  forProvider:
    size: 30
    subregionName: "eu-west-2a"
    volumeType: "gp2"
    tags:
      - key: Name
        value: cp-volume
  providerConfigRef:
    name: default 
