/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this NetPeering.
func (mg *NetPeering) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AccepterNetID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AccepterNetIDRef,
		Selector:     mg.Spec.ForProvider.AccepterNetIDSelector,
		To: reference.To{
			List:    &NetList{},
			Managed: &Net{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AccepterNetID")
	}
	mg.Spec.ForProvider.AccepterNetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AccepterNetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceNetID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SourceNetIDRef,
		Selector:     mg.Spec.ForProvider.SourceNetIDSelector,
		To: reference.To{
			List:    &NetList{},
			Managed: &Net{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceNetID")
	}
	mg.Spec.ForProvider.SourceNetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceNetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NetPeeringAcceptation.
func (mg *NetPeeringAcceptation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetPeeringID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NetPeeringIDRef,
		Selector:     mg.Spec.ForProvider.NetPeeringIDSelector,
		To: reference.To{
			List:    &NetPeeringList{},
			Managed: &NetPeering{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetPeeringID")
	}
	mg.Spec.ForProvider.NetPeeringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetPeeringIDRef = rsp.ResolvedReference

	return nil
}
