//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLogObservation) DeepCopyInto(out *AccessLogObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogObservation.
func (in *AccessLogObservation) DeepCopy() *AccessLogObservation {
	if in == nil {
		return nil
	}
	out := new(AccessLogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLogParameters) DeepCopyInto(out *AccessLogParameters) {
	*out = *in
	if in.IsEnabled != nil {
		in, out := &in.IsEnabled, &out.IsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OsuBucketName != nil {
		in, out := &in.OsuBucketName, &out.OsuBucketName
		*out = new(string)
		**out = **in
	}
	if in.OsuBucketPrefix != nil {
		in, out := &in.OsuBucketPrefix, &out.OsuBucketPrefix
		*out = new(string)
		**out = **in
	}
	if in.PublicationInterval != nil {
		in, out := &in.PublicationInterval, &out.PublicationInterval
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogParameters.
func (in *AccessLogParameters) DeepCopy() *AccessLogParameters {
	if in == nil {
		return nil
	}
	out := new(AccessLogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStickyCookiePoliciesObservation) DeepCopyInto(out *ApplicationStickyCookiePoliciesObservation) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStickyCookiePoliciesObservation.
func (in *ApplicationStickyCookiePoliciesObservation) DeepCopy() *ApplicationStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStickyCookiePoliciesParameters) DeepCopyInto(out *ApplicationStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStickyCookiePoliciesParameters.
func (in *ApplicationStickyCookiePoliciesParameters) DeepCopy() *ApplicationStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckObservation) DeepCopyInto(out *HealthCheckObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckObservation.
func (in *HealthCheckObservation) DeepCopy() *HealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckParameters) DeepCopyInto(out *HealthCheckParameters) {
	*out = *in
	if in.CheckInterval != nil {
		in, out := &in.CheckInterval, &out.CheckInterval
		*out = new(float64)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(float64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckParameters.
func (in *HealthCheckParameters) DeepCopy() *HealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerObservation) DeepCopyInto(out *ListenerObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerObservation.
func (in *ListenerObservation) DeepCopy() *ListenerObservation {
	if in == nil {
		return nil
	}
	out := new(ListenerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerParameters) DeepCopyInto(out *ListenerParameters) {
	*out = *in
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerPort != nil {
		in, out := &in.LoadBalancerPort, &out.LoadBalancerPort
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerParameters.
func (in *ListenerParameters) DeepCopy() *ListenerParameters {
	if in == nil {
		return nil
	}
	out := new(ListenerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerRuleObservation) DeepCopyInto(out *ListenerRuleObservation) {
	*out = *in
	if in.ListenerID != nil {
		in, out := &in.ListenerID, &out.ListenerID
		*out = new(float64)
		**out = **in
	}
	if in.ListenerRuleID != nil {
		in, out := &in.ListenerRuleID, &out.ListenerRuleID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerRuleObservation.
func (in *ListenerRuleObservation) DeepCopy() *ListenerRuleObservation {
	if in == nil {
		return nil
	}
	out := new(ListenerRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerRuleParameters) DeepCopyInto(out *ListenerRuleParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.HostNamePattern != nil {
		in, out := &in.HostNamePattern, &out.HostNamePattern
		*out = new(string)
		**out = **in
	}
	if in.ListenerRuleName != nil {
		in, out := &in.ListenerRuleName, &out.ListenerRuleName
		*out = new(string)
		**out = **in
	}
	if in.PathPattern != nil {
		in, out := &in.PathPattern, &out.PathPattern
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerRuleParameters.
func (in *ListenerRuleParameters) DeepCopy() *ListenerRuleParameters {
	if in == nil {
		return nil
	}
	out := new(ListenerRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenersObservation) DeepCopyInto(out *ListenersObservation) {
	*out = *in
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenersObservation.
func (in *ListenersObservation) DeepCopy() *ListenersObservation {
	if in == nil {
		return nil
	}
	out := new(ListenersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenersParameters) DeepCopyInto(out *ListenersParameters) {
	*out = *in
	if in.BackendPort != nil {
		in, out := &in.BackendPort, &out.BackendPort
		*out = new(float64)
		**out = **in
	}
	if in.BackendProtocol != nil {
		in, out := &in.BackendProtocol, &out.BackendProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerPort != nil {
		in, out := &in.LoadBalancerPort, &out.LoadBalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadBalancerProtocol != nil {
		in, out := &in.LoadBalancerProtocol, &out.LoadBalancerProtocol
		*out = new(string)
		**out = **in
	}
	if in.ServerCertificateID != nil {
		in, out := &in.ServerCertificateID, &out.ServerCertificateID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenersParameters.
func (in *ListenersParameters) DeepCopy() *ListenersParameters {
	if in == nil {
		return nil
	}
	out := new(ListenersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributes) DeepCopyInto(out *LoadBalancerAttributes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributes.
func (in *LoadBalancerAttributes) DeepCopy() *LoadBalancerAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerAttributes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesApplicationStickyCookiePoliciesObservation) DeepCopyInto(out *LoadBalancerAttributesApplicationStickyCookiePoliciesObservation) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesApplicationStickyCookiePoliciesObservation.
func (in *LoadBalancerAttributesApplicationStickyCookiePoliciesObservation) DeepCopy() *LoadBalancerAttributesApplicationStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesApplicationStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesApplicationStickyCookiePoliciesParameters) DeepCopyInto(out *LoadBalancerAttributesApplicationStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesApplicationStickyCookiePoliciesParameters.
func (in *LoadBalancerAttributesApplicationStickyCookiePoliciesParameters) DeepCopy() *LoadBalancerAttributesApplicationStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesApplicationStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesList) DeepCopyInto(out *LoadBalancerAttributesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerAttributes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesList.
func (in *LoadBalancerAttributesList) DeepCopy() *LoadBalancerAttributesList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerAttributesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesListenersObservation) DeepCopyInto(out *LoadBalancerAttributesListenersObservation) {
	*out = *in
	if in.BackendPort != nil {
		in, out := &in.BackendPort, &out.BackendPort
		*out = new(float64)
		**out = **in
	}
	if in.BackendProtocol != nil {
		in, out := &in.BackendProtocol, &out.BackendProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerPort != nil {
		in, out := &in.LoadBalancerPort, &out.LoadBalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadBalancerProtocol != nil {
		in, out := &in.LoadBalancerProtocol, &out.LoadBalancerProtocol
		*out = new(string)
		**out = **in
	}
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerCertificateID != nil {
		in, out := &in.ServerCertificateID, &out.ServerCertificateID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesListenersObservation.
func (in *LoadBalancerAttributesListenersObservation) DeepCopy() *LoadBalancerAttributesListenersObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesListenersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesListenersParameters) DeepCopyInto(out *LoadBalancerAttributesListenersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesListenersParameters.
func (in *LoadBalancerAttributesListenersParameters) DeepCopy() *LoadBalancerAttributesListenersParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesListenersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation) DeepCopyInto(out *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation) {
	*out = *in
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation.
func (in *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation) DeepCopy() *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters) DeepCopyInto(out *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters.
func (in *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters) DeepCopy() *LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesLoadBalancerStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesObservation) DeepCopyInto(out *LoadBalancerAttributesObservation) {
	*out = *in
	if in.ApplicationStickyCookiePolicies != nil {
		in, out := &in.ApplicationStickyCookiePolicies, &out.ApplicationStickyCookiePolicies
		*out = make([]LoadBalancerAttributesApplicationStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendVMIds != nil {
		in, out := &in.BackendVMIds, &out.BackendVMIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]LoadBalancerAttributesListenersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerStickyCookiePolicies != nil {
		in, out := &in.LoadBalancerStickyCookiePolicies, &out.LoadBalancerStickyCookiePolicies
		*out = make([]LoadBalancerAttributesLoadBalancerStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SourceSecurityGroup != nil {
		in, out := &in.SourceSecurityGroup, &out.SourceSecurityGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubregionNames != nil {
		in, out := &in.SubregionNames, &out.SubregionNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]LoadBalancerAttributesTagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesObservation.
func (in *LoadBalancerAttributesObservation) DeepCopy() *LoadBalancerAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesParameters) DeepCopyInto(out *LoadBalancerAttributesParameters) {
	*out = *in
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = make([]AccessLogParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerPort != nil {
		in, out := &in.LoadBalancerPort, &out.LoadBalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerCertificateID != nil {
		in, out := &in.ServerCertificateID, &out.ServerCertificateID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]LoadBalancerAttributesTagsParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesParameters.
func (in *LoadBalancerAttributesParameters) DeepCopy() *LoadBalancerAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesSpec) DeepCopyInto(out *LoadBalancerAttributesSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesSpec.
func (in *LoadBalancerAttributesSpec) DeepCopy() *LoadBalancerAttributesSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesStatus) DeepCopyInto(out *LoadBalancerAttributesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesStatus.
func (in *LoadBalancerAttributesStatus) DeepCopy() *LoadBalancerAttributesStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesTagsObservation) DeepCopyInto(out *LoadBalancerAttributesTagsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesTagsObservation.
func (in *LoadBalancerAttributesTagsObservation) DeepCopy() *LoadBalancerAttributesTagsObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesTagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributesTagsParameters) DeepCopyInto(out *LoadBalancerAttributesTagsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributesTagsParameters.
func (in *LoadBalancerAttributesTagsParameters) DeepCopy() *LoadBalancerAttributesTagsParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributesTagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRule) DeepCopyInto(out *LoadBalancerListernerRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRule.
func (in *LoadBalancerListernerRule) DeepCopy() *LoadBalancerListernerRule {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerListernerRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRuleList) DeepCopyInto(out *LoadBalancerListernerRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerListernerRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRuleList.
func (in *LoadBalancerListernerRuleList) DeepCopy() *LoadBalancerListernerRuleList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerListernerRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRuleObservation) DeepCopyInto(out *LoadBalancerListernerRuleObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ListenerRule != nil {
		in, out := &in.ListenerRule, &out.ListenerRule
		*out = make([]ListenerRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRuleObservation.
func (in *LoadBalancerListernerRuleObservation) DeepCopy() *LoadBalancerListernerRuleObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRuleParameters) DeepCopyInto(out *LoadBalancerListernerRuleParameters) {
	*out = *in
	if in.Listener != nil {
		in, out := &in.Listener, &out.Listener
		*out = make([]ListenerParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ListenerRule != nil {
		in, out := &in.ListenerRule, &out.ListenerRule
		*out = make([]ListenerRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VMIds != nil {
		in, out := &in.VMIds, &out.VMIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRuleParameters.
func (in *LoadBalancerListernerRuleParameters) DeepCopy() *LoadBalancerListernerRuleParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRuleSpec) DeepCopyInto(out *LoadBalancerListernerRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRuleSpec.
func (in *LoadBalancerListernerRuleSpec) DeepCopy() *LoadBalancerListernerRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerListernerRuleStatus) DeepCopyInto(out *LoadBalancerListernerRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerListernerRuleStatus.
func (in *LoadBalancerListernerRuleStatus) DeepCopy() *LoadBalancerListernerRuleStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerListernerRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerObservation) DeepCopyInto(out *LoadBalancerObservation) {
	*out = *in
	if in.ApplicationStickyCookiePolicies != nil {
		in, out := &in.ApplicationStickyCookiePolicies, &out.ApplicationStickyCookiePolicies
		*out = make([]ApplicationStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]ListenersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerStickyCookiePolicies != nil {
		in, out := &in.LoadBalancerStickyCookiePolicies, &out.LoadBalancerStickyCookiePolicies
		*out = make([]LoadBalancerStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetID != nil {
		in, out := &in.NetID, &out.NetID
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.SourceSecurityGroup != nil {
		in, out := &in.SourceSecurityGroup, &out.SourceSecurityGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerObservation.
func (in *LoadBalancerObservation) DeepCopy() *LoadBalancerObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerParameters) DeepCopyInto(out *LoadBalancerParameters) {
	*out = *in
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.BackendVMIds != nil {
		in, out := &in.BackendVMIds, &out.BackendVMIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]ListenersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(string)
		**out = **in
	}
	if in.SecuredCookies != nil {
		in, out := &in.SecuredCookies, &out.SecuredCookies
		*out = new(bool)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecurityGroupsRefs != nil {
		in, out := &in.SecurityGroupsRefs, &out.SecurityGroupsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityGroupsSelector != nil {
		in, out := &in.SecurityGroupsSelector, &out.SecurityGroupsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetsRefs != nil {
		in, out := &in.SubnetsRefs, &out.SubnetsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubnetsSelector != nil {
		in, out := &in.SubnetsSelector, &out.SubnetsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SubregionNames != nil {
		in, out := &in.SubregionNames, &out.SubregionNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]TagsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerParameters.
func (in *LoadBalancerParameters) DeepCopy() *LoadBalancerParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicy) DeepCopyInto(out *LoadBalancerPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicy.
func (in *LoadBalancerPolicy) DeepCopy() *LoadBalancerPolicy {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyApplicationStickyCookiePoliciesObservation) DeepCopyInto(out *LoadBalancerPolicyApplicationStickyCookiePoliciesObservation) {
	*out = *in
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyApplicationStickyCookiePoliciesObservation.
func (in *LoadBalancerPolicyApplicationStickyCookiePoliciesObservation) DeepCopy() *LoadBalancerPolicyApplicationStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyApplicationStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyApplicationStickyCookiePoliciesParameters) DeepCopyInto(out *LoadBalancerPolicyApplicationStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyApplicationStickyCookiePoliciesParameters.
func (in *LoadBalancerPolicyApplicationStickyCookiePoliciesParameters) DeepCopy() *LoadBalancerPolicyApplicationStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyApplicationStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyList) DeepCopyInto(out *LoadBalancerPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyList.
func (in *LoadBalancerPolicyList) DeepCopy() *LoadBalancerPolicyList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyListenersObservation) DeepCopyInto(out *LoadBalancerPolicyListenersObservation) {
	*out = *in
	if in.BackendPort != nil {
		in, out := &in.BackendPort, &out.BackendPort
		*out = new(float64)
		**out = **in
	}
	if in.BackendProtocol != nil {
		in, out := &in.BackendProtocol, &out.BackendProtocol
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerPort != nil {
		in, out := &in.LoadBalancerPort, &out.LoadBalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadBalancerProtocol != nil {
		in, out := &in.LoadBalancerProtocol, &out.LoadBalancerProtocol
		*out = new(string)
		**out = **in
	}
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerCertificateID != nil {
		in, out := &in.ServerCertificateID, &out.ServerCertificateID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyListenersObservation.
func (in *LoadBalancerPolicyListenersObservation) DeepCopy() *LoadBalancerPolicyListenersObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyListenersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyListenersParameters) DeepCopyInto(out *LoadBalancerPolicyListenersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyListenersParameters.
func (in *LoadBalancerPolicyListenersParameters) DeepCopy() *LoadBalancerPolicyListenersParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyListenersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation) DeepCopyInto(out *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation) {
	*out = *in
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation.
func (in *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation) DeepCopy() *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters) DeepCopyInto(out *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters.
func (in *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters) DeepCopy() *LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyLoadBalancerStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyObservation) DeepCopyInto(out *LoadBalancerPolicyObservation) {
	*out = *in
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ApplicationStickyCookiePolicies != nil {
		in, out := &in.ApplicationStickyCookiePolicies, &out.ApplicationStickyCookiePolicies
		*out = make([]LoadBalancerPolicyApplicationStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]LoadBalancerPolicyListenersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancerStickyCookiePolicies != nil {
		in, out := &in.LoadBalancerStickyCookiePolicies, &out.LoadBalancerStickyCookiePolicies
		*out = make([]LoadBalancerPolicyLoadBalancerStickyCookiePoliciesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetID != nil {
		in, out := &in.NetID, &out.NetID
		*out = new(string)
		**out = **in
	}
	if in.PublicIP != nil {
		in, out := &in.PublicIP, &out.PublicIP
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
	if in.SecuredCookies != nil {
		in, out := &in.SecuredCookies, &out.SecuredCookies
		*out = new(bool)
		**out = **in
	}
	if in.SourceSecurityGroup != nil {
		in, out := &in.SourceSecurityGroup, &out.SourceSecurityGroup
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]LoadBalancerPolicyTagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyObservation.
func (in *LoadBalancerPolicyObservation) DeepCopy() *LoadBalancerPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyParameters) DeepCopyInto(out *LoadBalancerPolicyParameters) {
	*out = *in
	if in.BackendVMIds != nil {
		in, out := &in.BackendVMIds, &out.BackendVMIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CookieExpirationPeriod != nil {
		in, out := &in.CookieExpirationPeriod, &out.CookieExpirationPeriod
		*out = new(float64)
		**out = **in
	}
	if in.CookieName != nil {
		in, out := &in.CookieName, &out.CookieName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerType != nil {
		in, out := &in.LoadBalancerType, &out.LoadBalancerType
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubregionNames != nil {
		in, out := &in.SubregionNames, &out.SubregionNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]LoadBalancerPolicyTagsParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyParameters.
func (in *LoadBalancerPolicyParameters) DeepCopy() *LoadBalancerPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicySpec) DeepCopyInto(out *LoadBalancerPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicySpec.
func (in *LoadBalancerPolicySpec) DeepCopy() *LoadBalancerPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyStatus) DeepCopyInto(out *LoadBalancerPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyStatus.
func (in *LoadBalancerPolicyStatus) DeepCopy() *LoadBalancerPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyTagsObservation) DeepCopyInto(out *LoadBalancerPolicyTagsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyTagsObservation.
func (in *LoadBalancerPolicyTagsObservation) DeepCopy() *LoadBalancerPolicyTagsObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyTagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPolicyTagsParameters) DeepCopyInto(out *LoadBalancerPolicyTagsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPolicyTagsParameters.
func (in *LoadBalancerPolicyTagsParameters) DeepCopy() *LoadBalancerPolicyTagsParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPolicyTagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStickyCookiePoliciesObservation) DeepCopyInto(out *LoadBalancerStickyCookiePoliciesObservation) {
	*out = *in
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStickyCookiePoliciesObservation.
func (in *LoadBalancerStickyCookiePoliciesObservation) DeepCopy() *LoadBalancerStickyCookiePoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStickyCookiePoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStickyCookiePoliciesParameters) DeepCopyInto(out *LoadBalancerStickyCookiePoliciesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStickyCookiePoliciesParameters.
func (in *LoadBalancerStickyCookiePoliciesParameters) DeepCopy() *LoadBalancerStickyCookiePoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStickyCookiePoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVms) DeepCopyInto(out *LoadBalancerVms) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVms.
func (in *LoadBalancerVms) DeepCopy() *LoadBalancerVms {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerVms) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVmsList) DeepCopyInto(out *LoadBalancerVmsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerVms, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVmsList.
func (in *LoadBalancerVmsList) DeepCopy() *LoadBalancerVmsList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVmsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerVmsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVmsObservation) DeepCopyInto(out *LoadBalancerVmsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.RequestID != nil {
		in, out := &in.RequestID, &out.RequestID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVmsObservation.
func (in *LoadBalancerVmsObservation) DeepCopy() *LoadBalancerVmsObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVmsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVmsParameters) DeepCopyInto(out *LoadBalancerVmsParameters) {
	*out = *in
	if in.BackendVMIds != nil {
		in, out := &in.BackendVMIds, &out.BackendVMIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BackendVMIdsRefs != nil {
		in, out := &in.BackendVMIdsRefs, &out.BackendVMIdsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendVMIdsSelector != nil {
		in, out := &in.BackendVMIdsSelector, &out.BackendVMIdsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVmsParameters.
func (in *LoadBalancerVmsParameters) DeepCopy() *LoadBalancerVmsParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVmsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVmsSpec) DeepCopyInto(out *LoadBalancerVmsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVmsSpec.
func (in *LoadBalancerVmsSpec) DeepCopy() *LoadBalancerVmsSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerVmsStatus) DeepCopyInto(out *LoadBalancerVmsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerVmsStatus.
func (in *LoadBalancerVmsStatus) DeepCopy() *LoadBalancerVmsStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerVmsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagsObservation) DeepCopyInto(out *TagsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagsObservation.
func (in *TagsObservation) DeepCopy() *TagsObservation {
	if in == nil {
		return nil
	}
	out := new(TagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagsParameters) DeepCopyInto(out *TagsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagsParameters.
func (in *TagsParameters) DeepCopy() *TagsParameters {
	if in == nil {
		return nil
	}
	out := new(TagsParameters)
	in.DeepCopyInto(out)
	return out
}
