apiVersion: vm.upjet-provider-outscale.upbound.io/v1alpha1
kind: Vm
metadata:
  name: vm
  namespace: default
spec:
  forProvider:
    imageId: "ami-bbe870d5"
    vmType: "tinav4.c1r1p2"
    keypairName: "crossplane"
    placementSubregionName: "us-east-2a"
    placementTenancy: "default"
  providerConfigRef:
    name: default
