/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/outscale-vbr/upjet-provider-outscale/apis/net/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this InternetServiceLink.
func (mg *InternetServiceLink) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InternetServiceID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.InternetServiceIDRef,
		Selector:     mg.Spec.ForProvider.InternetServiceIDSelector,
		To: reference.To{
			List:    &InternetServiceList{},
			Managed: &InternetService{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.InternetServiceID")
	}
	mg.Spec.ForProvider.InternetServiceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.InternetServiceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NetIDRef,
		Selector:     mg.Spec.ForProvider.NetIDSelector,
		To: reference.To{
			List:    &v1alpha1.NetList{},
			Managed: &v1alpha1.Net{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetID")
	}
	mg.Spec.ForProvider.NetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetIDRef = rsp.ResolvedReference

	return nil
}
