apiVersion: foo.bar/v1alpha1
kind: NetVm
metadata:
  namespace: default
  name: example
spec:
  parameters:
    subregionName: us-east-2a
    volumeSize: 10
    volumeType: "gp2"
    ipRanges: "0.0.0.0/0"
    vmType: "tinav4.c1r1p2"
    imageId: "ami-bbe870d5"
    netIpRange: "10.0.0.0/16"
    subnetIpRange: "10.0.0.0/24"
  compositionSelector:
    matchLabels:
      provider: outscale