apiVersion: subnet.upjet-provider-outscale.upbound.io/v1alpha1
kind: Subnet
metadata:
  name: subnet
  namespace: default
spec:
  forProvider:
    ipRange: "10.0.0.0/24"
    subregionName: "eu-west-2a"
    netIdRef: 
      name: net
    tags: 
      - key: Name
        value: subnet
  providerConfigRef:
    name: default 
