/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/outscale-vbr/upjet-provider-outscale/apis/vm/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PublicIpLink.
func (mg *PublicIpLink) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PublicIPID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PublicIPIDRef,
		Selector:     mg.Spec.ForProvider.PublicIPIDSelector,
		To: reference.To{
			List:    &PublicIpList{},
			Managed: &PublicIp{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PublicIPID")
	}
	mg.Spec.ForProvider.PublicIPID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PublicIPIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VMID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.VMIDRef,
		Selector:     mg.Spec.ForProvider.VMIDSelector,
		To: reference.To{
			List:    &v1alpha1.VmList{},
			Managed: &v1alpha1.Vm{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VMID")
	}
	mg.Spec.ForProvider.VMID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VMIDRef = rsp.ResolvedReference

	return nil
}
