name: test-terraform

on:
  push:
jobs:
  test-terraform:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout uppjet
      uses: actions/checkout@v3
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout osc-k8s-rke-cluster
      uses: actions/checkout@v3
      with:
        repository: 'outscale-dev/osc-k8s-rke-cluster'
        path: "rke-cluster-for-upjet"
        ref: master
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.22.7
      id: install
    - name: Install golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.7'
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1
    - name: Install first time pyenv
      uses: gabrielfalcao/pyenv-action@v11
      with:
        default: "3.10"
        command: pip install -U pip   
    - name: Clone Repository
      run: make clone
      env:
        git_full_local_path: /tmp/upjet-provider-outscale
        git_password: ${{ secrets.UPJET_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
    - name: Update Version
      run: |
        sudo pip3 install --ignore-installed -r requirements.txt
        make update
      env:
        IMG: 127.0.0.1:4242/upjet-provider-outscale:${{ github.sha }}
        DOCKER_BUILDKIT: 1
        git_full_local_path: /tmp/upjet-provider-outscale
        git_password: ${{ secrets.UPJET_TOKEN }}
    - name: Deploy Cluster
      uses: ./rke-cluster-for-upjet/github_actions/deploy_cluster/
      with:
        repository_folder: "rke-cluster-for-upjet"
        osc_access_key: ${{ secrets.OSC_ACCESS_KEY }}
        osc_secret_key: ${{ secrets.OSC_SECRET_KEY }}
        osc_region: ${{ secrets.OSC_REGION }}
        image_id: ${{ secrets.OMI_ID }}   
    - name: Install first time pyenv
      uses: gabrielfalcao/pyenv-action@v11
      with:
        default: "3.10"
        command: pip install -U pip   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
    - name: Update Version
      run: |
        sudo pip3 install --ignore-installed -r requirements.txt
        make update
      env:
        IMG: 127.0.0.1:4242/upjet-provider-outscale:${{ github.sha }}
        DOCKER_BUILDKIT: 1
        git_full_local_path: /tmp/upjet-provider-outscale
        git_password: ${{ secrets.UPJET_TOKEN }}
        OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
        OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        OSC_REGION: ${{ secrets.OSC_REGION }}   
    - name: Destroy cluster
      uses: ./rke-cluster-for-upjet/github_actions/destroy_cluster/
      if: ${{ always() }}
      with:
        repository_folder: "./rke-cluster-for-upjet"
        osc_access_key: ${{ secrets.OSC_ACCESS_KEY }}
        osc_secret_key: ${{ secrets.OSC_SECRET_KEY }}
        osc_region: ${{ secrets.OSC_REGION }}     
  
  