apiVersion: securitygroup.upjet-provider-outscale.upbound.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: cp-public-sg-rule
  namespace: default
spec:
  forProvider:
    flow: "Inbound"
    rules:
      - fromPortRange: 8080
        toPortRange: 8080
        ipProtocol: "tcp"
        ipRanges: 
        - "0.0.0.0/0"  
    securityGroupIdRef:
      name: cp-public-sg
  providerConfigRef:
    name: default
