apiVersion: subnet.upjet-provider-outscale.upbound.io/v1alpha1
kind: Subnet
metadata:
  name: cp-public-subnet
  namespace: default
spec:
  forProvider:
    ipRange: "10.0.0.0/24"
    subregionName: "us-east-2a"
    netIdRef: 
      name: cp-net
    tags: 
      - key: Name
        value: cp-public-subnet
  providerConfigRef:
    name: default 
